
server:
  port: 8002

spring:
  application:
    name: bank2-api
  main:
    allow-circular-references: true
  datasource:
    url: jdbc:mysql://localhost:3306/bank2?useSSL=false&createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update

uri:
  frontend: http://localhost:4201